Fix masked state on systemd-timesyncd
idiv-biodiversity/ansible-role-systemd-timesyncd pull request #5
Opened 2023-08-10 06:34 UTC by anesheret

Reinstall systemd-timesyncd service

Checked on Ubuntu 22.04 with installed `ntp` package and masked `systemd-timesyncd`

Resolves: #3

2023-08-15 11:33 UTC, wookietreiber requested changes

2023-08-15 11:33 UTC, wookietreiber commented on tasks/main.yml
> +    state: present
Please fix the issue as reported by ansible-lint: 

```
args[module]: value of state must be one of: started, stopped, reloaded, restarted, got: present (warning)
tasks/main.yml:39 Task/Handler: Install systemd-timesyncd
```

2023-08-15 11:40 UTC, wookietreiber commented on tasks/main.yml
> +    state: present
I guess you meant to use `ansible.builtin.package`?

2023-08-15 12:07 UTC, anesheret commented on tasks/main.yml
> +    state: present
My `ansible-lint` no report any issues (missconfigured). In last commit [9eeab04](https://github.com/idiv-biodiversity/ansible-role-systemd-timesyncd/pull/5/commits/9eeab04395b192c5da4462dee7e39355109cdb83) i'm change package to service.
Ok, i will revert them.

2023-08-22 09:40 UTC, wookietreiber commented
I've taken the time to add verification of the role via molecule, rewritten a major part of the tasks, and just released the changes as v1.3.0. This also includes a switch in the vars to install `systemd-timesyncd` on Ubuntu Jammy. It's very likely that this already fixed #3, and with these changes that we don't need this PR anymore. Can you confirm this on your end?

2023-09-01 10:27 UTC, anesheret commented
Checked, worked as expected! Tanks.

2023-09-01 10:27 UTC, closed without merging